config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]
  root  to:'home#index'
  get'/posts' , to: 'posts#all_posts' , as: 'all_posts'
  resources :topics do
    resources :posts do
      patch 'mark_as_read', on: :member
      resources :comments do
        resources :user_comment_ratings
      end
      resources :ratings, only: [:create]
    end
  end
  resources :tags do
    member do
      get 'posts', to: 'tags#posts', as: 'posts'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post ,counter_cache: true
  belongs_to :user
  has_many :user_comment_ratings, dependent: :destroy
  has_many :rating_users, through: :user_comment_ratings, source: :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  load_and_authorize_resource
  before_action :set_topic
  before_action :set_post
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = @post.comments.includes([:user]).all
    @ratings = Comment.joins(:user_comment_ratings).distinct
  end
  def ratings
    @comment = Comment.find(params[:id])
    @ratings = @comment.user_comment_ratings
  end
  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user =current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_post_comments_url(@topic, @post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to topic_post_comment_url(@topic, @post), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to topic_post_comments_url(@topic, @post), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def set_post
    @post = @topic.posts.find(params[:post_id])
  end

  def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@topic, @post, @comment]) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="text-center">
    <%= form.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Back', topic_post_comments_path(@topic, @post), class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="container">
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

</div>

app/views/comments/index.html.erb
<div class="container">
  <%= notice.present? ? "<h6 id='notice' class='alert alert-info'>#{notice}</h6>".html_safe : '' %>

  <h1>Comments</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Content</th>
      <th>User Email</th>
      <th>Add Ratings</th>
      <th class="text-center" colspan="3">Action</th>
    </tr>
    </thead>

    <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user.present? ? comment.user.email : 'No user ID' %></td>
        <td>
          <%= form_for([@topic, @post, comment, UserCommentRating.new], url: topic_post_comment_user_comment_ratings_path(comment.post.topic, comment.post, comment), remote: true) do |f| %>
            <%= f.hidden_field :comment_id, value: comment.id %>
            <div class="form-group">
              <%= f.label :value %>
              <%= f.select :value, (1..5).to_a, prompt: 'Select a rating', class: 'form-control' %>
            </div>

            <%= f.submit 'Rate Comment', class: 'btn btn-primary' %>
          <% end %>
        </td>

        <td><%= link_to 'Show', topic_post_comment_path(@topic, @post, comment), class: 'btn btn-outline-info' %></td>
        <td><%= link_to 'Edit', edit_topic_post_comment_path(@topic, @post, comment), class: 'btn btn-outline-warning' if can?(:edit, comment)&.present? %></td>
        <td><%= button_to 'Destroy', topic_post_comment_path(@topic, @post, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Comment', new_topic_post_comment_path(@topic, @post), class: 'btn btn-outline-success' %>
  <%= link_to 'Back', topic_post_path(@topic, @post), class: 'btn btn-outline-secondary' %>
</div>

app/views/comments/new.html.erb
<div class="container">
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_topic_post_comment_path(@topic, @post, @comment) if can?(:edit, @comment)&.present? %> |
<%= link_to 'Back', topic_post_comments_path(@topic,@post) %>