config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]
  root  to:'home#index'
  get'/posts' , to: 'posts#all_posts' , as: 'all_posts'
  resources :topics do
    resources :posts do
      patch 'mark_as_read', on: :member
      resources :comments do
        resources :user_comment_ratings
      end
      resources :ratings, only: [:create]
    end
  end
  resources :tags do
    member do
      get 'posts', to: 'tags#posts', as: 'posts'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts ,dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic, html: { class: 'needs-validation' }) do |form| %>
  <% if topic.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, class: 'form-control-label' %>
    <%= form.text_field :title, class: 'form-control', required: true %>
    <div class="invalid-feedback">Please provide a title.</div>
  </div>
<br>
  <div class="form-group">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
    <%= link_to 'Back', topics_path, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="container">
  <h1 class="mt-4 mb-4">Editing Topic</h1>

  <%= render 'form', topic: @topic %>
</div>

app/views/topics/index.html.erb
<div class="container">
  <%= notice.present? ? "<h6 id='notice' class='alert alert-info'>#{notice}</h6>".html_safe : '' %>
  <h1 class="mt-4 mb-4">Topics</h1>

  <table class="table">
    <thead>
    <tr>
      <th><h4>Title</h4></th>
      <th class="text-center" colspan="3"><h4>Actions</h4></th>
    </tr>
    </thead>

    <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><strong><%= topic.title %></strong></td>
        <td class="text-center" colspan="3">
          <%= link_to 'Show', topic, class: 'btn btn-outline-primary btn-sm me-5' %>
          <%= link_to 'Edit', edit_topic_path(topic), class: 'btn btn-outline-secondary btn-sm me-5' %>
          <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Topic', new_topic_path, class: 'btn btn-outline-success' %>
  <%= link_to 'Back to home',root_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/topics/new.html.erb
<div class="container">
  <h1 class="mt-4 mb-4">New Topic</h1>

  <%= render 'form', topic: @topic %>

</div>

app/views/topics/show.html.erb
<div class="container">
  <%= notice.present? ? "<h6 id='notice' class='alert alert-info'>#{notice}</h6>".html_safe : '' %>
<br>
  <h5>
    <strong>Title:</strong>
    <%= @topic.title %>
  </h5>
<br>
  <%= link_to 'Posts', topic_posts_path(@topic), class: "btn btn-outline-primary" %> |
  <%= link_to 'Edit', edit_topic_path(@topic), class: "btn btn-outline-warning" %> |
  <%= link_to 'Back', topics_path, class: "btn btn-outline-secondary" %>
</div>