config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]
  root  to:'home#index'
  get'/posts' , to: 'posts#all_posts' , as: 'all_posts'
  resources :topics do
    resources :posts do
      patch 'mark_as_read', on: :member
      resources :comments do
        resources :user_comment_ratings
      end
      resources :ratings, only: [:create]
    end
  end
  resources :tags do
    member do
      get 'posts', to: 'tags#posts', as: 'posts'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]


  def index
    @tags =Tag.all
  end
  def new
    @tag =Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    post_page_url = params[:tag][:post_page_url]
    respond_to do |format|
      if @tag.save
        format.html { redirect_to post_page_url, notice: 'Tag was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def show

  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    post_page_url = params[:tag][:post_page_url]
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to post_page_url, notice: 'Tag was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  def destroy
    @tag.destroy
    redirect_to tags_url ,notice: "tag deleted"
  end
  def posts
    @tag = Tag.find(params[:id])
    @posts = @tag.posts.includes([:topic])
  end

  private

  def set_tag
    @tag =Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/views/tags/_form.html.erb
<%= form_with(model: @tag, local: true) do |form| %>
  <%= form.hidden_field :post_page_url, value: request.referer %>
    <% if @tag.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

        <ul>
          <% @tag.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>

<%= render 'form'  %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<div class="container">
  <h1>All Tags</h1>
  <h6 class="text-success"><%= params[:notice] %></h6>
  <div class="mb-3">
    <%= link_to "Create New Tag", new_tag_path, class: "btn btn-outline-primary" %>
  </div>

  <table class="table table-hover">
    <thead>
    <tr>
      <th>Tag</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><strong><%= link_to tag.name,  posts_tag_path(tag) %></strong></td>
        <td><%= link_to "Edit", edit_tag_path(tag), class: "btn btn-outline-secondary btn-sm" %></td>
        <td><%= button_to "Delete", tag, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/tags/new.html.erb
<h3>New tag</h3>
<%= render 'form' %>

<%= link_to "back to tag",tags_path %>

app/views/tags/posts.html.erb
<div class="text">
  <div class="container mt-4">
    <h1>Posts with Tag: <%= @tag.name %></h1>
    <ul class="list-group">
      <% @posts.each do |post| %>
        <li class="list-group-item">
          <%= link_to post.title, topic_post_path(post.topic, post) %>
        </li>
      <% end %>
    </ul>
    </div> <br><br>
  <%= link_to "Back to tags",tags_path,class: "btn btn-secondary"  %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<%= link_to "Edit" ,edit_tag_path(@tag) %>
<%= link_to "Back", tags_path %>