config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]
  root  to:'home#index'
  get'/posts' , to: 'posts#all_posts' , as: 'all_posts'
  resources :topics do
    resources :posts do
      patch 'mark_as_read', on: :member
      resources :comments do
        resources :user_comment_ratings
      end
      resources :ratings, only: [:create]
    end
  end
  resources :tags do
    member do
      get 'posts', to: 'tags#posts', as: 'posts'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  has_many :comments , dependent: :destroy
  has_many :post_tags
  has_many :tags, through: :post_tags
  paginates_per 3
  has_many :ratings
  has_one_attached :image
  belongs_to :user
  has_many :posts_users_read_statuses
  has_many :readers, through: :posts_users_read_statuses, source: :user
  def marked_as_read?(user)
    readers.includes([:readers]).include?(user)
  end
  def mark_as_read(user)
    posts_users_read_statuses.find_or_create_by(user: user).update(read: true)
  end
  scope :filter_by_date, ->(from_date, to_date) {
    where(created_at: from_date.beginning_of_day..to_date.end_of_day)
  }
  after_create :update_rating_average
  def update_rating_average
    update_column(:rating_average, ratings.average(:value))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_topic , except: :all_posts
  include CanCan::ControllerAdditions
  load_and_authorize_resource
  # GET /posts or /posts.json
  def index
    @posts = @topic.posts.all
  end
  def all_posts
    from_date = params[:from_date].presence || 1.day.ago.to_date
    to_date = params[:to_date].presence || Date.today
    from_date = Date.parse(from_date.to_s)
    to_date = Date.parse(to_date.to_s)

    @posts=Post.includes([:topic])
               .filter_by_date(from_date, to_date).
      page(params[:page]).per(3)
  end
  # GET /posts/1 or /posts/1.json
  def show
    @ratings = @post.ratings.group(:value).count
  end
  def mark_as_read
    @post = Post.find(params[:id])
    @post.mark_as_read(current_user) if user_signed_in?
    respond_to do |format|
      format.js
    end
  end
  # GET /posts/new
  def new
    @post = @topic.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = @topic.posts.build(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to topic_posts_path(@topic, @post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to topic_post_path(@topic,@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.tags.clear
    @post.ratings.destroy_all
    @post.destroy

    respond_to do |format|
      format.html { redirect_to topic_posts_path(@topic), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :topic_id ,:image, tag_ids: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: [@topic, @post]) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <%= render "image_preview", form: form, post: @post %>

  <div class="mb-3">
    <%= form.label :tag_ids, "Tags :", class: "form-label" %>
    <div class="d-flex flex-wrap">
      <% Tag.all.each do |tag| %>
        <div class="form-check me-3 mb-2">
          <%= form.check_box :tag_ids, { multiple: true, class: "form-check-input" }, tag.id, nil %>
          <%= label_tag "post_tag_ids_#{tag.id}", tag.name, class: "form-check-label ms-2" %>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to "Create new tags", new_tag_path, class: "btn btn-outline-primary mb-2" %>

  <div class="actions">
    <%= form.submit "Save Post", class: "btn btn-success" %>
    <%= link_to 'Back', topic_posts_path(@topic), class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/posts/_image_preview.html.erb
  <%= form.label :image %>


  <%= form.file_field :image,
                      direct_upload:true,
                      data:{previews_target:"input",action: "change->previews#preview"},
                      class: "form-control" %>

  <% if @post.image.attached? %>
    <%= image_tag @post.image,data: { previews_target: "preview"},class: "image"%>
  <%else %>
    <%= image_tag "",data: { previews_target: "preview"},class: "image"%>
  <%end %>

app/views/posts/all_posts.html.erb
<div class="container">
  <%= notice.present? ? "<h6 id='notice' class='alert alert-info'>#{notice}</h6>".html_safe : '' %>

  <h1>Posts</h1>

  <%= form_tag(all_posts_path, method: :get) do %>
    <div class="row mb-3">
      <div class="col">
        <%= label_tag 'From Date:' %>
        <%= date_field_tag 'from_date', params[:from_date], class: 'form-control' %>
      </div>
      <div class="col">
        <%= label_tag 'To Date:' %>
        <%= date_field_tag 'to_date', params[:to_date], class: 'form-control ' %>
      </div>
      <div class="col">
        <%= submit_tag 'Show Details', class: 'btn btn-primary mb-3' %>
      </div>
    </div>
  <% end %>

  <table class="table">
    <thead>
    <tr>
      <th>Title (Topic)</th>
      <th>Content</th>
      <th>Status</th>
      <th>Created at</th>
      <th>Avg rating</th>
      <th>Comments count</th>
    </tr>
    </thead>

    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= "#{post.title} (#{post.topic.title})" %></td>
        <td><%= post.content %></td>
        <td><%= post.marked_as_read?(current_user) ? 'Read' : 'Unread' %></td>
        <td><%= post.created_at.to_date %></td>
        <td><%= post.rating_average.present? ? "#{post.rating_average.round(1)} Ratings" : 'N/A' %></td>
        <td><%= post.comments_count %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= paginate @posts %>


  <br>
</div>

app/views/posts/edit.html.erb
<div class="container">
<h1 class="mb-4">Editing Post</h1>
<%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <%= notice.present? ? "<h6 id='notice' class='alert alert-info'>#{notice}</h6>".html_safe : '' %>

  <h1>Posts</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Topic</th>
      <th>Status</th>
      <th>Avg rating</th>
      <th>Comments count</th>
      <th class="text-center" colspan="3">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.topic.title %></td>
        <td><%= post.marked_as_read?(current_user) ? 'Read' : 'Unread' %></td>
        <td><%= post.rating_average.present? ? " #{post.rating_average.round(1)} Ratings" : 'N/A' %></td>
        <td><%= post.comments_count %></td>
        <td><%= link_to 'Show', topic_post_path(@topic, post), class: 'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to 'Edit', edit_topic_post_path(@topic, post), class: 'btn btn-outline-secondary btn-sm' if can?(:edit, post)&.present? %></td>
        <td><%= button_to 'Destroy', topic_post_path(@topic, post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_topic_post_path(@topic), class: 'btn btn-outline-success' %>
  <%= link_to 'Back', topics_path(@topic), class: 'btn btn-outline-secondary' %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="mt-4 mb-4">New Post</h1>

  <%= render 'form'%>


</div>

app/views/posts/show.html.erb
<div class="container">
  <br>
<%= notice.present? ? "<h6 id='notice' class='alert alert-info'>#{notice}</h6>".html_safe : '' %>

<script>
    $(document).ready(function() {
        var loggedIn = <%= user_signed_in? %>;

        if (loggedIn) {
            var csrfToken = $('meta[name=csrf-token]').attr('content');

            $.ajax({
                url: "/topics/<%= @topic.id %>/posts/<%= @post.id %>/mark_as_read",
                type: "PATCH",
                headers: {
                    'X-CSRF-Token': csrfToken
                },
                success: function(response) {
                    console.log("Post marked as read");
                    // You can update the UI as needed
                },
                error: function(error) {
                    console.error("Error marking post as read");
                }
            });
        }
    });
</script>
  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @post.content %>
  </p>

  <p><strong>User Email:</strong> <%= @post.user.present? ? @post.user.email : 'No User ID' %></p>

  <p><strong>Status:</strong> <%= @post.marked_as_read?(current_user) ? 'Read' : 'Unread' %></p>

  <p>
    <strong>Tags:</strong>
    <% if @post.tags.any? %>
      <% @post.tags.each do |tag| %>
        <%= tag.name %>
      <% end %>
    <% else %>
      No tags available for this post.
    <% end %>
  </p>

  <% if @post.image.attached? %>
    <%= image_tag(@post.image, class: "img-fluid") %>
  <% else %>
    <strong>No images added</strong>
  <% end %>

  <br><br>

  <p><strong>Ratings:</strong></p>
  <ul>
    <% @ratings.each do |star, count| %>
      <li><%= star %> Star Ratings: <%= count %></li>
    <% end %>
  </ul>

  <%= form_for([@topic, @post, @post.ratings.build]) do |f| %>
    <h6><%= f.label :value %></h6>
    <%= f.radio_button :value, 1 %> 1 Star
    <%= f.radio_button :value, 2 %> 2 Stars
    <%= f.radio_button :value, 3 %> 3 Stars
    <%= f.radio_button :value, 4 %> 4 Stars
    <%= f.radio_button :value, 5 %> 5 Stars
    <%= f.submit "Submit Rating", class: "btn btn-primary" %>
  <% end %>

  <br>

  <%= link_to 'Edit', edit_topic_post_path(@topic, @post), class: "btn btn-outline-warning " if can?(:edit, @post)&.present? %>
  <%= link_to 'Show Comments', topic_post_comments_path(@topic, @post), class: "btn btn-outline-primary" %>
  <%= link_to 'Back', topic_posts_path(@topic), class: 'btn btn-outline-secondary' %>
</div>